### PR TITLE
First Metabolomcis ReDU Conversion to SDRF

### PR DESCRIPTION
**Pull request by mwang87**

### CODE REVIEW

**Comment by ypriverol** [comment]
@timosachsenberg @levitsky @pcm32 @daichengxin @anjaf We need feedback here. We are extending the file format for metabolomics (@mwang87 has a lot of data that he wants to push) and we need some feedback from you guys.

**Comment by ypriverol** [comment]
My review @mwang87 : 

- [  ] While is most of the cases we allow non available, in this repo we aim to capture at least some metadata 😉. I recommend to at least capture the organism, organism part etc. 
- [  ] I strongly recommend to call the sample (`source name`) in a different way rather than the RAW file name. It can be a simple autonumeric like Sample 1, Sample 2, etc. 
- [  ] Instrument can't be written in that way. It should be `NT=impact;AC=MS:1002077`
-

**Review by ypriverol — CHANGES_REQUESTED** [review]
My review @mwang87 : 

- [ ] While is most of the cases we allow non available, in this repo we aim to capture at least some metadata 😉. I recommend to at least capture the organism, organism part etc. 
- [ ] I strongly recommend to call the sample (`source name`) in a different way rather than the RAW file name. It can be a simple autonumeric like Sample 1, Sample 2, etc. 
- [ ] Instrument can't be written in that way. It should be `NT=impact;AC=MS:1002077`
- [ ]  comment[label] should be `AC=MS:1002038;NT=label free sample`
- [ ] the data file is the name of the file, not directory structure. 

@mwang87 these are some comments from a quick first review. We can continue improving the example. This is the first metabolomics experiment, them some information probably is relevant for metabolomics that we are not capturing and you should suggest them.

**Comment by ypriverol** [comment]
@daichengxin can you check why the validator said OK to this datasets even when label is not here, replicates are missing and instrument is written is a very strange way.

**Comment by daichengxin** [comment]
SDRF file not found because the file name suffix @ypriverol .
https://github.com/bigbio/proteomics-metadata-standard/blob/4b9eb3de2363b3d278167bb824d9ce8d287f562b/validate.py#L127

**Comment by daichengxin** [comment]
If there are study variables in the metabolome experiment, The variable/property under study SHOULD be highlighted using the factor value category. factor value” columns SHOULD indicate which experimental factor/variable is used as the hypothesis to perform the data analysis. But this is not Mandatory 😉. @mwang87

**Comment by anjaf** [comment]
From the biological annotations, indeed it looks like there is still some room for improvement. 
Why are the first couple of files "organism: not applicable"? It says in the file name "human_swap". 
So at least we can add "organism: Homo sapiens", and "sex: male/female" (also found in the file name). 
It would be desirable to go beyond the attributes listed in the file names and try to find out what was the input material that was analysed. If this is different to gene or protein analysis, you may come up with a controlled vocabulary or ontology to define suitable terms for this. For example what does "swap" mean, where/when/how was it taken? 
On the level of the experimental design, it will be good to know any experimental factors (perturbations, time series etc). And identifying the source organism/sample, e.g. if several samples were taken from the same donor, it make sense to include a donor ID. 

On the technical side, I would recommend to include some field by which proteomics and metabolomics studies can be identified. @ypriverol Do you use something like "technology type" field? In ArrayExpress we have "Technology Type" in the SDRF with "array assay" or "sequencing assay" as values, so we can distinguish sequencing vs. microarray experiments. Here, we could go for "technology type: metabolomics assay" or in EFO there is assay type "[metabolomic profiling](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0000752&viewMode=All&siblings=false)".

**Comment by mwang87** [comment]
@ypriverol comments

1. Organism is captured, some samples are not applicable, but others are listed as Homo Sapiens
2. What are the semantics of source name? We could just strip off the full path, these files don't really have a sample identifier within ReDU
3. We can fix the instrument format, but the validator didn't have an issue with the current format
4. We can add that
5. OK we can change that

Additionally

@daichengxin this is for ReDU so we won't have any experimental factors here. However, we have other metadata that is experiment specific where we can add those. 

@anjaf The not applicable is just how the user originally entered it.

**Comment by mwang87** [comment]
@ypriverol We've made updates here. I have a few questions, 

1. Is the validator in pip different than the validator in github actions? 
2. Why is biologicla replicate a characteristic, but technical replicate a comment?

**Comment by ypriverol** [comment]
@mwang87 responses inline: 


> @ypriverol comments
> 
> 1. Organism is captured, some samples are not applicable, but others are listed as Homo Sapiens

Is perfectly fine, @anjaf can you let us know what will be the best option when no species is applicable. For example, for `natural products` in metaboligths. 

> 2. What are the semantics of source name? We could just strip off the full path, these files don't really have a sample identifier within ReDU

This is backward compatibility with MAGE-TAB in transcriptomic. Is the way is called the sample. 
> 3. We can fix the instrument format, but the validator didn't have an issue with the current format

You need to rename all the files to `NAMEPROJECT.sdrf.tsv` we need the extension .sdrf.tsv

> 4. We can add that

Thanks 

> 5. OK we can change that
> 

Thanks 

> Additionally
> 
> @daichengxin this is for ReDU so we won't have any experimental factors here. However, we have other metadata that is experiment specific where we can add those.

In recent calls, Nuno suggested having factor value required. I guess we need some way to name what are you trying to study. We can work in that issue at the end. 

> 
> @anjaf The not applicable is just how the user originally entered it.

**Pull request closed without merging**
