### PR TITLE
PXD004143-sdrf

### PR DESCRIPTION
**Pull request by deeptijk**

### CODE REVIEW

**Comment by deeptijk** [comment]
@ypriverol I couldn't understand the error. Please let me know what's the issue. I hope I am not doing any basic mistake again.

**Comment by deeptijk** [comment]
@ypriverol Please merge this sdrf into master.

**Comment by deeptijk** [comment]
@ypriverol Please merge this project.

**Review by ypriverol — CHANGES_REQUESTED** [review]
please rename test.tsv -> sdrf.tsv

**Comment by deeptijk** [comment]
@ypriverol please merge this PXD002029 project sdrf annotation file

**Comment by deeptijk** [comment]
@ypriverol I just create test.tsv first to upload my sdrf.tsv. I then delete it from the project folder. There are only sdrf.tsv files are present in all my uploaded projects. Till now I have uploaded 4 annotated projects. Please merge them. 
1. PXD002029
2. PXD007160
3. PXD006233
4. PXD004143

**Review by ypriverol — CHANGES_REQUESTED** [review]
Can you replace label free -> NT=label free sample

**Review by ypriverol — APPROVED** [review]

**Pull request merged**
