### PR TITLE
Annotation of PXD005463

### PR DESCRIPTION
**Pull request by Luxxii**

### CODE REVIEW

**Comment by Luxxii** [comment]
Hi!

i have appended the missing lines. As i understand it: each line corresponds to either the light or heavy sample in one Raw-File (with `factor value[label]`). The `assay name` here references it, that they have been retrieved by the same run (so 3 Raw-FIles in Total). Please correct me if i am wrong.

I am also a little bit confused about the Pipeline throwing an Error:

Both ontologies do exist, but only the `heavy` one is found.

Here the Links:
Light: https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002614&viewMode=All&siblings=false
Heavy: https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002612&viewMode=All&siblings=false

**Comment by levitsky** [comment]
> As i understand it: each line corresponds to either the light or heavy sample in one Raw-File (with `factor value[label]`).

Yes, as we put it: each row represents a relationship between a sample and a raw file.
Also, if you only have one light and one heavy sample in each assay, then my understanding is that you only need one `comment[label]` column. For one sample it will say "light" and for the other one "heavy".

As for factor value: unless you are studying labeling itself, I don't think it makes sense to put `label` there. You should put the actual sample `characteristic` that differs between samples and the effect of which you are studying.

As for pipeline errors, the correct terms for SILAC labels are listed in the [PRIDE ontology](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000328&viewMode=All&siblings=false). There was a discussion in #327 about the need for more specific labels that "light" and "heavy".

**Comment by Luxxii** [comment]
The `comment[label]` column has been updated. I added more specific information there. 

I also added `comment[dissociation method]`.

Thank you for the clarification. I hope this is now correct especially with the SILAC-labels

**Comment by levitsky** [comment]
Thank you! A couple of other issues/suggestions, since this is a cell culture (this is just my opinion):

- `organism part` should not be `cell culture`, rather `not applicable`;
- `disease` should be `not applicable`, not `not available`;
- `developmental stage` should be `not applicable`, not `not available`;
- in modifications, `TA` should be a one-letter code (`TA=R`, not `TA=Arg`);
- also, according to [the docs](https://github.com/bigbio/proteomics-metadata-standard/tree/master/sample-metadata#encoding-protein-modifications), the terminal modifications should use `PP`. I am not sure what `TA` should say, though. Do we need to allow some kind of a wildcard for TA, like `*`, or make TA optional? what is the convention here? @ypriverol

**Comment by Luxxii** [comment]
I changed to `TA=*` in the terminal modification and the pipeline ran without errors.

It has been changed to some columns to `not applicable" as suggested by you.

**Review by levitsky — CHANGES_REQUESTED** [review]
Thank you!
In the last row, though, I see that the modification is on `Lys` (not `K` and not `R`). It should be corrected to one of these for consistency.

My last concern is again about `factor value`, apart from my previous comment, the values now don't coincide with the `label` column. Also, there are two label columns but only one factor value, which doesn't quite make sense. So, my suggestion remains as before, to not use `factor value` to repeat the label unless this is a study on labeling itself.

**Review by levitsky — APPROVED** [review]

**Pull request merged**
