### PR TITLE
Adds PMID27251275 (CPTAC-TMT)

### PR DESCRIPTION
**Pull request by rudnickp**
First pass at annotating the CPTAC3 Prospective Breast Cancer Study.
Note: this study has a bunch of QC-disqualified samples, but all have been included for completeness.
Needs better use of CV terms as well as links to term identifiers.

### CODE REVIEW

**Comment by ypriverol** [comment]
@rudnickp TMT channels can be found here: 

https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000515

Some examples: `TMT126`

**Comment by foellmelanie** [comment]
wow, what a giant annotation file! The only thing I spotted is the comment[modification parameters] for the TMT labels is missing.

**Comment by ypriverol** [comment]
@rudnickp can you check some of the information that is still missing. PTMs etc.

**Comment by ypriverol** [comment]
@rudnickp sorry to push more should I merge the PR?

**Pull request merged**
