### PR TITLE
adding PXD006877

### PR DESCRIPTION
**Pull request by StSchulze**
This is an archaeal dataset, using SILAC labeling (#311).
The implementation of the SILAC labeling annotation still needs to be discussed, but the other parts of the SDRF should be fine and can be checked.

### CODE REVIEW

**Comment by ypriverol** [comment]
@StSchulze check the PR https://github.com/PRIDE-Utilities/pride-ontology/pulls if it looks ok, I can merge the PR and we can start using it.

**Comment by ypriverol** [comment]
@StSchulze can you check the last whitespace in the label. It needs to be removed.

**Comment by StSchulze** [comment]
Removed it, but the term unfortunately still can't be found in the ontology.

**Comment by ypriverol** [comment]
It will be picked but OLS within this week.

**Pull request merged**
