### PR TITLE
major changes

### PR DESCRIPTION
**Pull request by ypriverol**
Major changes related with the following issue: 

- https://github.com/bigbio/proteomics-metadata-standard/issues/167
- https://github.com/bigbio/proteomics-metadata-standard/issues/33
- https://github.com/bigbio/proteomics-metadata-standard/issues/168

### CODE REVIEW

**Comment by ypriverol** [comment]
@levitsky can you review this PR.

**Comment by levitsky** [comment]
> @levitsky can you review this PR.

I don't see any problems. I think it can be merged, any minor issues can be ironed out later.

(I also think it's cleaner if the PRs are done via a different branch, so you don't need to sync it and add unrelated commits to the PR.)

**Comment by ypriverol** [comment]
@levitsky this PR is related to 4 issues #222 #220 #218 #149 . It will close all of them automatically I think.

**Comment by levitsky** [comment]
I don't think it will, from what I have read about automatic issue linking. But if so, #222 we will have to reopen.

**Comment by levitsky** [comment]
OK, you were right :)

**Comment by ypriverol** [comment]
Let's try to discuss issue #222.

**Pull request merged**
