### PR TITLE
annotated PXD002870

### PR DESCRIPTION
**Pull request by enriquea**

### CODE REVIEW

**Comment by enriquea** [comment]
PXD002870

**Comment by ypriverol** [comment]
The labeling in this experiment is confusing is done with deuterium. We don't have a proper definition for this in PRIDE ontology.

**Comment by timosachsenberg** [comment]
Hi Enrique!
I found some minor issue like having additional quotes: 
"NT=Phospho;MT=variable;TA=S,T,Y;AC=UNIMOD:21"

Yes, dynamic labeling with deuterium is kind of a special analysis. Could make sense to add a dedicated quantification method column for that

**Comment by ypriverol** [comment]
@timosachsenberg in the other labeling methods, we have label names such as: 

TMT{X1}, TMT{X2}.. .

SILAC heavy, SILAC light 

What should be the label in this case. ?

**Comment by timosachsenberg** [comment]
I would say the label is just deuterium but one needs to distinguish between different methods that replace H by deuterium.
There is e.g. "stable isotope probing" or "H/D exchange" that differ in how they introduce deuterium and afaik they are analyzed quite differently

**Comment by ypriverol** [comment]
> I would say the label is just deuterium but one needs to distinguish between different methods that replace H by deuterium.
> There is e.g. "stable isotope probing" or "H/D exchange" that differ in how they introduce deuterium and afaik they are analyzed quite differently

The parent term in the ontology could be `Deuterium`. Inside multiple labels can be used to classify the specific label: 

- Deuterium H/D exchange 
- Deuterium stable isotope probing 

It is difficult for me which are the two stages in this method look like the sample with the labeling `2H2O labeling` and the other one no?

**Comment by timosachsenberg** [comment]
in stable isotope probing, you might have one protein with 0.1% labeling, one with 10% one with 20% ...
so there are not really distinct states like SILAC.
Better to think about it as a different way of quantifying. But instead of abundances, you might quantify i.e. the relative isotope abundance.

**Comment by enriquea** [comment]
> Hi Enrique!
> I found some minor issue like having additional quotes:
> "NT=Phospho;MT=variable;TA=S,T,Y;AC=UNIMOD:21"
> 
> Yes, dynamic labeling with deuterium is kind of a special analysis. Could make sense to add a dedicated quantification method column for that

Hi Timo,

Thanks! I will correct that.

**Comment by ypriverol** [comment]
@timosachsenberg If I understand correctly one thing is the label and the other is the parameters associated with it like you said: 

> isotope probing, you might have one protein with 0.1% labeling, one with 10% one with 20% ...

First thing we need to define is the label for these types of experiments, then we need to define what properties will be needed to understand the experiment.

**Comment by ypriverol** [comment]
@timosachsenberg I added a new term the PRIDE ontology called Deuterium label sample, see PR here https://github.com/PRIDE-Utilities/pride-ontology/pull/41

**Comment by javizca** [comment]
Maybe Deuterium labelled sample?
(or labeled)

**Comment by ypriverol** [comment]
I tried to be compatible with the label-free annotation in ols: 

https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1002038&viewMode=All&siblings=false

**Comment by ypriverol** [comment]
Probably better to move from Deuterium label sample -> Deuterium https://github.com/PRIDE-Utilities/pride-ontology/pull/42

**Pull request merged**
