### PR TITLE
adding PXD000527 (iTRAQ)

### PR DESCRIPTION
**Pull request by foellmelanie**
- used both available unimods for iTRAQ8: 730,731
- allowed iTRAQ modifications of n-terminus and lysine (would be great if someone could verify that this is ok)

### CODE REVIEW

**Comment by levitsky** [comment]
Not about iTRAQ, but things that caught my eye:

- it's `developmental stage` in EFO, not `development stage`;
- using `pool` for things like `developmental stage` and `disease` should rather be `not applicable`, I think. Alternatively, if the pool is of these known samples, as per comments in #223 you can repeat all those samples and link them to the assay and file for the pooled sample;
- biological replicate should be [characteristics rather than comment](https://github.com/bigbio/proteomics-metadata-standard/issues/267).

**Comment by levitsky** [comment]
Great! One other thing I notice is a rather free use of `disease`. I have no knowledge of the context here, but:

1. Again, "pooled" should not be in there; it can be in "source name" but for disease it would be "not applicable" I think.
2. "Sterile" and "fertile" - these sound more like `phenotype` in this case, am I mistaken? Note that you absolutely don't need to use `disease` for plans, or maybe even shouldn't (?).
3. What exactly is `G1`, `HBP` etc.? Is it perhaps `strain/breed` or something to that effect applicable to plants?

**Comment by ypriverol** [comment]
@foellmelanie is the PR ready?

**Comment by foellmelanie** [comment]
Not yet... @ypriverol 

I am still not sure if TA=K for iTRAQ modification is correct or not. 
Also, if using both unimod 730 and 731 iTRAQ modifications is how we want to handle iTRAQ.
And I need to check the other comments from levitsky

**Comment by foellmelanie** [comment]
@levitsky @ypriverol 

I used characteristics[disease] because it is specified in the template. It's true that in this case phenotype is more suitable. 
It might be more common that investigated plants have different phenotypes than diseases - not sure, maybe you know someone doing plant proteomics and change the template accordingly?

**Comment by foellmelanie** [comment]
included @levitsky suggestions. I interpreted G1HBP as genotype and used sterile/fertile as phenotype. 

Before merging I would like someone to confirm: 
--> TA=K for iTRAQ modification is correct or not?
--> using both unimod 730 and 731 iTRAQ modifications is how we want/should to handle iTRAQ?

**Comment by ypriverol** [comment]
I guess in every sample we will have both ITRAQ PTMs. Then is fine to use both PTMs as variable modifications.

**Pull request merged**
