### PR TITLE
Addresses #306 First annotation of PXD006003

### PR DESCRIPTION
**Pull request by jgriss**

### CODE REVIEW

**Comment by jgriss** [comment]
Hi @ypriverol,

I tried to annotate as much clinical information as possible. Therefore, I added the column `characteristic[response to antineoplastic agent]` (which actually is an ontology term).

Is that invalid in the format? If yes, how should I annotate such additional clinical information?

Thanks for the help!

**Comment by ypriverol** [comment]
This term is probably better https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0042493&viewMode=All&siblings=false @anjaf

**Comment by levitsky** [comment]
@jgriss The error you see on the Github check is probably because you named the column `characteristic` rather than `characteristics`.

Values like `Y`, `N`, `NA` and `none` do not perfectly fit the general guidelines, as we tend not to use simple yes/no (I think), and `NA` and `none` should usually be something out of `not applicable` and `not available`, but the validator will not complain about that.

**Comment by jgriss** [comment]
@ypriverol @levitsky Thanks for the quick feedback! Updated version is committed.

**Comment by jgriss** [comment]
@ypriverol @levitsky One additional question: Since it's a super SILAC setup, I need one column to specify the label for the reference sample. For the original samples, this should be left empty. Should I use another term than `not applicable` in this case?

**Comment by ypriverol** [comment]
@jgriss yes not applicable is fine.

**Comment by jgriss** [comment]
@ypriverol If you need any changes in the file still just let me know!

**Comment by ypriverol** [comment]
It is still failing, `characteristics[ancestry category]` is missing and the label can't be not applicable.

**Comment by jgriss** [comment]
@ypriverol Thanks for the quick update! Changes are committed

**Pull request merged**
