### PR TITLE
First pubmed paper added

### PR DESCRIPTION
**Pull request by ypriverol**
This PR contains the first dataset, which is a reanalysis of an existing dataset in PRIDE but the data is not deposited again. The folder accession then is the Pubmed ID.

### CODE REVIEW

**Comment by ypriverol** [comment]
Hi @levitsky: 

Here some of my thoughts. 

> I had some questions, but I mostly answered them myself:
> 
> 1. So, the idea is to have a unified annotation for all data considered in a study, potentially from multiple PRIDE datasets or subsets thereof, is that right?
Yes
>    What if part of the data is taken from outside of PRIDE, maybe other repositories?

In this particular paper, they took the data from PRIDE but also from Chorus. As a policy, We SHOULD accept data from any repository as soon as a URL point to a public RAW file. In this particular study, the authors use private data in Chorus, that is the main reason why I didn't use it. 

> 2. Why is `source name` the same for all rows if these are different pools?

True, I will fix that. 

> 3. The use of `characteristics[pool]` for mixed samples makes sense, but it has not been discussed in #223.

Pool here is more a characteristic a name like pool 1, pool 2 but not a mix of samples.

**Comment by levitsky** [comment]
Another question now that I look at the file: some fields are quoted and some not, should it be consistent?

**Comment by ypriverol** [comment]
The PR is failing but everything is ok @levitsky

**Comment by levitsky** [comment]
Ah, that's because I undid your change that excluded "not found" from errors, because it wasn't doing anything, but then you renamed wrong files and now they are not found again.

**Comment by ypriverol** [comment]
We are still waiting to fix this problem. then we need to keep it

**Comment by levitsky** [comment]
For this reason there was a warning in #258 that merging it would result in errors :)

**Comment by ypriverol** [comment]
Sorry

**Pull request merged**
