### PR TITLE
Pxd004732

### PR DESCRIPTION
**Pull request by patroklossam**

### CODE REVIEW

**Comment by ypriverol** [comment]
@patroklossam @levitsky This is a more generic question about how do we encode columns value that has some dependencies. As far As I understood @anjaf the original SDRF gave the possibility to encode relation between columns by using consecutive columns meaning in this case: 

|comment[fragmentation methods] |comment[collation energy] |comment[fragmentation methods]   | comment[collation energy]
|-----------------------------------|----------------------------|---------------------------|----|
|HCD                                    | 28 NCE                                  | CID       | 23 NCE | 

This is achieved in SDRF by starting each combination with a `Node` head. Let said you have the combination of multiple parameters, you can prefix each combination with a `ProtocolRef` and an identifier for the protocol ref, in that case, the reader needs to know that whatever you found after that belongs to the same protocol (next figure)  

image

In our specific problem, this will be represented as: 

|ProtocolRef|comment[fragmentation methods] |comment[collation energy] |ProtocolRef|comment[fragmentation methods]   | comment[collation energy] |
|-|-----------------------------------|-------|---------------------|---------------------------|----|
|first_fractionation_step|HCD                                    | 28 NCE                                  | second_fractionation_step|CID       | 23 NCE |

**Comment by levitsky** [comment]
I _think_ I understand what you mean. In my opinion the first snippet you show would be acceptable in this specific case, and I thought about using the column order, as well, but I came to think my suggestion would work better, at least in this case.

I think there are two upsides to using specialized terms as I suggested:
1. No need to keep strict column order.
 By using specialized terms we get rid of the need to encode the relationship between columns, they are independent and can be ordered more freely. This also means easier parsing logic.
2. It's more explicit.
 The column header explicitly states what the value means, as it should. No need to look at other columns.

Then there is one difference that is not to a clear advantage of either method:
Since in some files CID or HCD was used 2 or 3 times with different energies, with "column order" scheme you'd need to repeat the same `fragmentation method` value each time for each energy, using more values per row. 
With specific terms you get more columns (for specialized terms) but you don't repeat yourself in each row.
I think keeping each method's energy in its own column helps because the columns are homogeneous and easier to interpret.

Finally, the obvious downside to the suggestion with specialized terms is that we need to add those terms. But I don't see any other disadvantages and I think it results in a more readable structure generally.

**Comment by ypriverol** [comment]
@levitsky can you add an example of how this will be looking at the end? . Also can you list all the terms that are needed to modify accordingly the PRIDE ontology?

**Comment by levitsky** [comment]
OK, let's see. I'm going to try annotating two files, the first and the last rows in the table.

Your scheme would look like this (I think):

comment[dissociation method] | comment[collision energy] | comment[dissociation method] | comment[collision energy]  | comment[dissociation method] | comment[collision energy] | comment[dissociation method] | comment[collision energy]
---------------------------------- | ----------------------------- | ---------------------------------- | ------------------------------------ | ----------------------------------- | ------------------------------------ | ---------------------------------- | ------------------------------------
AC=MS:1000133;NT=CID | 35 NCE | AC=MS:1000422;NT=HCD | 20 NCE | AC=MS:1000422;NT=HCD  | 23 NCE | AC=MS:1000422;NT=HCD | 28 NCE
AC=MS:1000598;NT=ETD | 28 NCE | AC=MS:1002631;NT=EThcD | 28 NCE | AC=PRIDE:0000592;NT=ETciD | 35 NCE

Same two files under my scheme:

comment[dissociation method] | comment[dissociation method] | comment[dissociation method]  | comment[CID collision energy] | comment[HCD collision energy] | comment[HCD collision energy] | comment[HCD collision energy] | comment[EThcD collision energy] |  comment[ETciD collision energy] 
---------------------------------- | ----------------------------- | ---------------------------------- | ------------------------------------ | ----------------------------------- | ------------------------------------ | ---------------------------------- | ------------------------------------ | ------------------------------------
AC=MS:1000133;NT=CID | AC=MS:1000422;NT=HCD | | 35 NCE | 20 NCE | 23 NCE | 28 NCE | |
AC=MS:1000598;NT=ETD | AC=MS:1002631;NT=EThcD | AC=PRIDE:0000592;NT=ETciD | | | | | 28 NCE | 35 NCE

I think all the needed terms needed are those I used above: one for each method that uses collisions (CID, HCD, EThcD, ETciD). Are there any others?
Is it going to be the PRIDE ontology, though? `collision energy` is in `MS`.

**Comment by ypriverol** [comment]
- PRIDE ontology is better in this stage because we can modify (add/modify) terms more quickly. 
- How the parser of the file will now that the two columns are related? I guess the HCD collision energy should be a child term of HCD in the ontology?

**Comment by levitsky** [comment]
In my mind we would just add them under "collision energy".

There would be no direct way to see the relationship with the corresponding fragmentation method, but I don't think it helps much if we nest the collision energy under the method. You still need to apply some human perception to understand exactly what this relationship is. I think it's not worth bending the logic to do this.
There is no direct way to see the connection between MS2 analyzer and the fragmentation method,  either; it requires some common knowledge. Still, we don't nest one under the other in the ontology.

**Comment by patroklossam** [comment]
And what about ETD that is set to "auto" for the collision energy? in that case we need to use free text instead of a value and unit.

**Comment by ypriverol** [comment]
@patroklossam auto means something in the instrument no?

**Comment by patroklossam** [comment]
After talking to a my colleague: 
its an automated reaction time based on the current calibration and precursor charge (edited) 
https://link.springer.com/article/10.1007/s13361-015-1183-1
was pioneered by the coon lab as ETD is a chemical reaction that is depended on 4 parameters: How much precursor ions with which charge do I react with how much reagent for which time period
and that is calibrated during calibration for different charge states and effectively there are different reaction times for each charge state

**Comment by ypriverol** [comment]
In those cases that the value are unknown, the readers and bioinformatics tools at the end can not make sense out of the data if you put auto. Then we can put `not applicable` because not value is provided.

**Comment by levitsky** [comment]
I think if this information needs to be encoded, it needs its own term and column. I'm not comfortable with writing ETD reaction time under collision energy, because it's a completely different parameter with different units.
Since I'm advocating that even collision energies get their own specific terms in this case, in line with that I would suggest a separate term for "ETD reaction time" with possible values, apparently, being time periods in milliseconds and `auto`. (This suggestion holds even if collision energies do not get their own terms.)

**Comment by ypriverol** [comment]
@levitsky we probably need to think more about the combination of terms, because the number of CVTerms can start growing really quickly.

**Comment by lisavetasol** [comment]
@ypriverol @levitsky 
Just my two cents. 
1. I think it's a good idea to have specification terms (like collision energy, reaction time etc.) under a specific fragmentation type. It would be quite nice and easy to look up in the ontology - you chose "HCD" and see right away what you can/should specify for this fragmentation type. 

2. For different fragmentation types, there should be different parameters to specify. Let's say 'collision energy' for all collision activation (CID, HCD, and combination types), 'activation time' for ETD, voltage for SID, wavelength and impulse power for UVPD and so on. It may look like a lot, but there are many experimental parameters and if you're aiming to capture them - there will be lots of terms. Although I don't think it's too much. 
To be fair I don't think for ETD the different time activation can be used somehow in the analysis (like MS/MS spectra prediction), but in this case, I prefer to be inclusive. 

3. Also I don't think it hurts to have not just "collision energy", but "collision energy CID" and "collision energy HCD" to be able to parse without any columns dependency.

**Comment by ypriverol** [comment]
PR here https://github.com/PRIDE-Utilities/pride-ontology/pull/41 @lisavetasol @levitsky. The PRIDE Ontology as EFO has multiple terms from different ontologies.

**Comment by lisavetasol** [comment]
@ypriverol 
> PR here PRIDE-Utilities/pride-ontology#41 @lisavetasol @levitsky. The PRIDE Ontology as EFO has multiple terms from different ontologies.

For me looks good, I think it's a really proper way to do that. 

What's do you think about ETD activation time? Also I'm pretty sure that UVPD needs wavelength and pulse power, but it can be added later when there will be some UVPD datasets?

**Comment by ypriverol** [comment]
We can do it after if you are fine with that!!!

**Comment by levitsky** [comment]
I think it looks great. "is a" and "part of" are exactly what I was trying to say :)

There is no term for ETD reaction time there, though. Since it doesn't change in this dataset, I'm not sure if we have the use case for annotation, but I don't really have an opinion on that.

**Comment by ypriverol** [comment]
@patroklossam you can update now the files the new terms are: 

- AC=PRIDE:0000593; NT=CID collision energy
- AC=PRIDE:0000594; NT=HCD collision energy
- AC=PRIDE:0000595; NT=EThcD collision energy
- AC=PRIDE:0000596; NT=ETciD collision energy

Nice

**Comment by patroklossam** [comment]
nice, I will do it and push my changes! Thanks to all of you!
Just to clarify the different collision energies 
    AC=PRIDE:0000593; NT=CID collision energy
    AC=PRIDE:0000594; NT=HCD collision energy
    AC=PRIDE:0000595; NT=EThcD collision energy
    AC=PRIDE:0000596; NT=ETciD collision energy
will be separate columns right? with comment[CID collision energy] etc. 
correct?

**Comment by levitsky** [comment]
@patroklossam yes, and some of them can be repeated to include multiple values, as shown in my small example in the comment [here](https://github.com/bigbio/proteomics-metadata-standard/pull/285#issuecomment-635658310) (second table).

**Comment by patroklossam** [comment]
let me know if this is fine so that I can change accordingly the other PR!

**Pull request merged**
