### PR TITLE
PXD007160-SDRF

### PR DESCRIPTION
**Pull request by deeptijk**

### CODE REVIEW

**Comment by deeptijk** [comment]
@ypriverol Couldn't find the validation error although it was fine when I validated it locally.

**Comment by ypriverol** [comment]
@deeptijk:

- Can you rename the file to sdrf.tsv

**Comment by deeptijk** [comment]
Have a look now. I have changed the name and provided the factor value

**Comment by deeptijk** [comment]
@ypriverol please merge the sdrf.tsv. It has passed the validation.

**Pull request merged**
