### PR TITLE
Added spec update about how to annotate PDX

### PR DESCRIPTION
**Pull request by jgriss**
This is an update to the documentation to detail how to annotate PDX samples based on the discussion in #363

### CODE REVIEW

**Comment by jgriss** [comment]
Hi @levitsky,

The intention was different. When processing primary tumour samples, the `source name` is the identifier of that tumour sample. In my case the PDX were derived from exactly these tumours. Therefore, the `characteristics[individual]` links to the `source name` of the original tumour sample.

I personally would not create another `patient unique ID`. Take, for example, the case where two tumours are taken from the same patient at different time points (we had such a study) and you derive PDX from each of them. Linking to the patient wouldn't help because all metadata (treatment annotations, timepoint) are only relevant to that tumour, which is identified through the `source name`.

But maybe you have a suggestion of how to rephrase the spec to make this a bit more clear?

**Comment by levitsky** [comment]
It's not that I misunderstand your suggested documentation change. My understanding is that the idea of using identical `characteristics[individual]` was suggested in #306 [here](https://github.com/bigbio/proteomics-metadata-standard/issues/306#issuecomment-651712566) and [here](https://github.com/bigbio/proteomics-metadata-standard/issues/306#issuecomment-651800170):
> I think `characteristics[individual]` should be the same for the PDX and primary tumour. That is what allows their matching.

> Regarding the primary vs PDX samples, yes, including `Characteristics[individual]` with the same (donor) ID is the best way to capture the relationship between the samples.

Note, it's "the same (donor) ID" and not the sample ID (source name).

All I'm saying about "linking" the source name from the `characteristics[individual]` field is that I did not see it discussed before and it looks like the suggestion in #306 was not that. If I'm not mistaken in this, should we maybe discuss this a bit more?

**Comment by jgriss** [comment]
Hi @levitsky,

You are right. Maybe we can have the discussion right as part of this PR?

Essentially, we should use `characteristics[individual]` to link samples through some kind of donor id.

Additionally, we might want to think about a recommended column to link samples that are derived from the same actual sample (ie linking a PDX to its tumour of origin).

@ypriverol @mlocardpaulet @veitveit @anjaf @StSchulze what do you think?

**Comment by mlocardpaulet** [comment]
@jgriss: I just understood your problem of matching! Sorry it took me so long.. You mean matching some proteomics data on the original tumour sample with some data coming from the PDX after the experiment in the mouse? Super tricky. I guess in this situation you could have 2 `characteristics[individual]`, right? The one for the mouse that received the PDX, and the one from the Human the tumour comes from. 
Would this be possible?

**Comment by levitsky** [comment]
My understanding of the problem is that annotating the PDX sample with the donor ID is not enough because there may be multiple primary tumor samples (e.g. taken at different time points) associated with one donor and we would need to tie the PDX sample to the primary tumor sample, not just to the donor. Is that correct?

If so, I see two approaches theoretically. One is to use the source name of samples, as suggested. In this case, though, I would rather not use `characteristics[individual]` and use some special term for this. I don't see any reason why `individual` should be the term to use here, such usage would bend its meaning and be confusing generally. Ideally, it would be best to have a specialized, clearly named term like `characteristics[primary tumor sample]`.

Alternatively, we could replicate all the necessary metadata that identifies the primary sample in the PDX sample annotation. For one or two extra characteristics it is manageable, but gets harder with even more complex experimental designs.

**Comment by jgriss** [comment]
@mlocardpaulet @levitsky 

@levitsky is right. The "issue" is that multiple tumours may have been taken from the same patient but at different time points.

I like @levitsky's suggestion:

  * `characteristics[individual]` should be used to link samples coming from the same patient / donor
  * `characteristics[NEW TERM]` should be used to link parts of the same sample

The term `primary tumour` is not ideal since it refers to the original tumour (ie tumour vs. metastasis).

How about using `characteristics[original]` (ie [NCIT:C25604](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C25604))?

**Comment by jgriss** [comment]
Hi @mlocardpaulet @levitsky @ypriverol 

I've adapted the spec to reflect the latest proposal.

`characteristics[inidivual]` SHOULD be used to reference the patient.

`characteristics[original]` SHOULD be used to reference the sample of origin (if applicable).

**Comment by levitsky** [comment]
Oh and another question: do we plan to add an ontology term for `characteristics[original]`? Or link it to some existing term?

**Comment by ypriverol** [comment]
We need to create the PRIDE ontology term for it. Because no terms are present in EFO for this concept..

**Comment by levitsky** [comment]
Do you think `original` is a clear name? Should we maybe expand it a bit? What is the noun to use with `original` here?

Maybe something like `original source name`? Then it would be more obvious that the content is a `source name`. On the other hand, in the context of the ontology and not in SDRF context this wouldn't make sense.

**Comment by ypriverol** [comment]
Yes `original source name` looks better. Whatdo you think @jgriss

**Comment by jgriss** [comment]
I fully agree! `original source name` is a much better choice. I've adapted the specification - also to include the statement that non-PDX samples should have `not applicable` there as well.

**Comment by ypriverol** [comment]
I have added the `original source name` to PRIDE ontology.

**Pull request merged**
