### PR TITLE
added PXD005300

### PR DESCRIPTION
**Pull request by veitveit**

### CODE REVIEW

**Comment by levitsky** [comment]
I don't think you really added the enzyme there.
Also, is it right that the first file has different modification parameters from the others?
And I think it should be `TA=K,R` rather than `PP=KR`.

**Comment by veitveit** [comment]
Sorry, messed up the files as I forgot to fork, will do that now

**Comment by levitsky** [comment]
This is almost perfect! But still, it should be `TA=K,R`, not `PP=`K,R`. And I'd just ask you to confirm if that's correct that the first file was searched with different modifications from the rest of the dataset.

**Comment by veitveit** [comment]
Thanks! Now I also found the documentation. This should be placed more visible.
Also some kind of summary could be useful, e.g. by describing all different search parameters, used instruments, ... 
Otherwise it is difficult to spot errors

**Comment by levitsky** [comment]
Absolutely. I also hope we'll do much more with automated validation.

**Comment by levitsky** [comment]
Factor values are great! But I think in brackets you need to put the characteristic that it is repeating, i.e. `factor value[organism part]` instead of `factor value[tissue]` in this case.

**Comment by levitsky** [comment]
Of course at the last moment I noticed one more thing: `developmental stage` is `not applicable`, why is that? If age is known, it should be possible (even if maybe not so important) to specify developmental stage. I'm guessing, 3 to 24 months are adults?

**Comment by veitveit** [comment]
Not sure about the 3 months, but the rest yes. I couldn't make much out of the available terms out of this category which is why I decided to use not applicable.

**Pull request merged**
