### PR TITLE
more datasets 

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by ypriverol** [comment]
@Douerww the species in this project do not exist in NCBI. Probably @anjaf can help us to define which species can be use for that kind of projects.

**Comment by anjaf** [comment]
I would go for annotating this as "human gut metagenome" https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=408170 (it has "human gut microbiota" as synonym). I think this comes closest. Make sure to keep the original more detailed annotation under some other (custom) Characteristics heading, if that's allowed.

**Comment by Douerww** [comment]
I'm modifying srdf.tsv after discussing with Dai Chengxin, and I will send you the revised version later. Then let's see if it's right.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bigbio/proteomics-metadata-standard"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 下午5:03
收件人:&nbsp;"bigbio/proteomics-metadata-standard"<proteomics-metadata-standard@noreply.github.com&gt;;
抄送:&nbsp;"D"<31438843@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bigbio/proteomics-metadata-standard] more datasets  (#513)





 
I would go for annotating this as "human gut metagenome" https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&amp;id=408170 (it has "human gut microbiota" as synonym). I think this comes closest. Make sure to keep the original more detailed annotation under some other (custom) Characteristics heading, if that's allowed.

**Comment by ypriverol** [comment]
@Douerww can you do that in my branch? @daichengxin knows what I mean.

**Comment by Douerww** [comment]
OK, please wait a moment.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bigbio/proteomics-metadata-standard"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月3日(星期三) 下午5:10
收件人:&nbsp;"bigbio/proteomics-metadata-standard"<proteomics-metadata-standard@noreply.github.com&gt;;
抄送:&nbsp;"D"<31438843@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [bigbio/proteomics-metadata-standard] more datasets  (#513)





 
@Douerww can you do that in my branch? @daichengxin knows what I mean.

**Pull request closed without merging**
