### PR TITLE
PXD001558 issue #324

### PR DESCRIPTION
**Pull request by mlocardpaulet**
I was not sure about the field characteristics[enrichment process]. I put "TIO2". It is peptide enrichment and not protein enrichment (as stated in the example). Let me know if I need to change it.

### CODE REVIEW

**Comment by mlocardpaulet** [comment]
But this is not Protein enrichment at all. This is different. It is phospho-PEPTIDE enrichment.

**Comment by ypriverol** [comment]
Well, the words probably are not the best but the intension is to use that value for phospho enrichment detection on proteomics experiments. 

> But this is not Protein enrichment at all. This is different. It is phospho-PEPTIDE enrichment.

**Comment by mlocardpaulet** [comment]
> Well, the words probably are not the best but the intension is to use that value for phospho enrichment detection on proteomics experiments.
> 
> > But this is not Protein enrichment at all. This is different. It is phospho-PEPTIDE enrichment.

Huummm... But the 2 exist and are very different. Can I use "enrichment of phosphorylated Peptides"?

**Comment by mlocardpaulet** [comment]
SILAC019 is just the name of the experiment.

**Comment by mlocardpaulet** [comment]
> If not label is applied to the sample, it should be described as label-free.

"label free" or "SILAC light"? Because it is in a SILAC triple labels experiment.

**Comment by ypriverol** [comment]
SILAC light

**Pull request merged**
