### PR TITLE
major changes in dataset annotation 

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by levitsky** [comment]
Great!

Although per README it should be just `none` or the compound without the prefix `compound: ` in all cells (I think we discussed this somewhere already).

Also there is a typo in `not applicable` (should be two `p`).

Finally, do we need "not available" as placeholder in repeated columns? In this case, modification parameters. It's probably not that important, but I just left the extra cells empty in this case, is that bad?

**Comment by ypriverol** [comment]
fixed typo

**Comment by levitsky** [comment]
Cool, what about compound? The readme has:

characteristics[compound] | 
---|
drug A |
none |

**Comment by ypriverol** [comment]
Fix the `characteristics[compound]`

**Pull request merged**
