### PR TITLE
First proposal for synthetic datasets

### PR DESCRIPTION
**Pull request by ypriverol**
The following dataset annotation contains a proposal for annotation of synthetic peptide libraries: 

- For synthetic peptide libraries, a new characteristics[synthetic peptide] will be used, the value for the samples will be: `no synthetic` or `synthetic`.

- We need to define the different types of enrichment methods for phospho-proteomics in PRIDE Cv.

### CODE REVIEW

**Comment by ypriverol** [comment]
@lisavetasol here the PR with the new phosphor methods https://github.com/PRIDE-Utilities/pride-ontology/pull/39

**Comment by ypriverol** [comment]
> As for the HeLa part, I can repeat my comment about ancestry category for HeLa from #276.
> 

DONE 

> As for the synthetic part, here are some questions/suggestions from my personal perspective:
> 
> 1. May I suggest using `not synthetic` rather than `no synthetic`?
Agree. 
> 2. Will this factor be added to EFO?

It is not in EFO, but I think we should leave some characteristics to be able to do not be in EFO. However, IF we need the term on EFO, we can collect a list of terms and request them with @anjaf. 

> 3. It makes more sense to say to say that age, sex, disease, organism part, ancestry category, cell line, cell type, developmental stage are `not applicable` to synthetic peptides, rather than `not available`.

Agreed, Just changed. 

> 4. I'm not sure if specifying the organism makes any sense for them either. Logically speaking, I think it is also `not applicable`.

This is more complex because normally these pools of peptides are coming from one specific species (in some cases). I mean, are peptides that reflect a species peptide Space. 

> 5. I think we need a separate template and set of mandatory columns for synthetic data sets. The only mandatory columns should be those from the default template and 
`characteristics[synthetic peptide]` (as long as we agree on item 4, i.e. that this is not human).

Agree, I think we should first create a section in the specification exampling the fields and then point the users to the template.

**Comment by ypriverol** [comment]
EFO requested terms pending here in this PR https://github.com/bigbio/proteomics-metadata-standard/pull/279

**Comment by levitsky** [comment]
Just in case you missed item 1 there, I just think `not synthetic` would be less confusing.

> It is not in EFO, but I think we should leave some characteristics to be able to do not be in EFO. However, IF we need the term on EFO, we can collect a list of terms and request them with @anjaf.

I like how the standard confines the space of possible column names now, I think it makes a lot of sense to keep it that way. Perhaps more or less arbitrary `comment` fields are okay, but `characteristics` should be limited to a structured, non-repeating list of factors, the best way would be to keep them in one ontology or a very small number of them.

>> I'm not sure if specifying the organism makes any sense for them either. Logically speaking, I think it is also not applicable.
>
> This is more complex because normally these pools of peptides are coming from one specific species (in some cases). I mean, are peptides that reflect a species peptide Space.

Yes, but still the relationship between the sample and the organism is not the same as for biological samples. Biological samples reflect the complete complexity of proteins and peptides in a particular part of the organism, or a collection thereof. For synthetic peptides, we only use a subset of a list of some representative peptides, which can be completely arbitrary.

I guess it is straightforward to interpret if `organism` is specified, but `not applicable` should also be allowed in this case.

**Comment by ypriverol** [comment]
I have changed from no synthetic -> not synthetic

**Pull request merged**
